### PR TITLE
kate devels asked for kate to be removed

### PR DESCRIPTION
**Pull request by tsdgeos**
https://bugs.kde.org/show_bug.cgi?id=431223

### CODE REVIEW

**Comment by tsdgeos** [comment]
@hfiguiere this failed to build, should i leave the json file even if it's not used?

**Comment by hfiguiere** [comment]
you don't remove the manifest. a build still need to happen.

Having the repository archived at the github level will remove the listing, but it has to be done after this is marked as eol.

**Comment by hfiguiere** [comment]
btw some of the issues like runing git are perfectly solvable. Even without having git built into the flatpak.

Require a bit of wrapper scripts, so a bit of initial work on the flatpak side.

**Comment by hfiguiere** [comment]
If GNOME Builder can run from a flatpak, this is solvable.

**Comment by tsdgeos** [comment]
running git is just the tip of the iceberg.

kate has an embedded terrninal where the user can run arbitrary commands needed to built their project. That's just not doable in flatpak, i would even say per design.

**Comment by hfiguiere** [comment]
> running git is just the tip of the iceberg.
> 
> kate has an embedded terrninal where the user can run arbitrary commands needed to built their project. That's just not doable in flatpak, i would even say per design.

Yet it works in GNOME Builder (I use it only as a Flatpak). There is possibly work needed on the backend / upstream.

(not trying to argue the removal here, it's your choice ultimately)

**Comment by tsdgeos** [comment]
Fair enough, i would like for things to work, but they don't and noone is going to do the job to make them work.

**Comment by tsdgeos** [comment]
@barthalion the howto says to ping an admin after removing an app, so ping :)

**Comment by bilelmoussaoui** [comment]
Will archive it.

**Pull request merged**
