### PR TITLE
Add support for markdown preview

### PR DESCRIPTION
**Pull request by JBBgameich**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Team lets have the discussion at https://invent.kde.org/teams/flathub/issues/-/issues/2 whether it makes sense to have this or not

**Comment by tsdgeos** [comment]
Can you please try to use https://download.kde.org/stable/markdownpart/0.1.0/src/ instead of kmarkdownwebview ?

It should give you the same features without depending on webengine that is a great improvement :)

**Comment by JBBgameich** [comment]
I'm installing the 5.15 Sdk right now to do this :)

**Comment by JBBgameich** [comment]
Everything builds fine, however the markdownpart didn't load in my testing. Instead kate claimed no preview was available.

**Comment by JBBgameich** [comment]
It works now after disabling and re-enabling the document preview plugin. Perhaps it was still looking for markdownwebview.

**Comment by tsdgeos** [comment]
Yes, sadly flatpak marks all files being created on january 1st 1970, so our cache mechanism for plugins gets confused by it. 

If you can't get it to work, you need to remove $HOME/.var/app/org.kde.kate/cache

**Pull request merged**
